@startuml
class button
class keyManager
class oncebutton
class ChordButtonManager
class Button2Chord

button <|-- oncebutton
ChordButtonManager *-- button
keyManager *-- oncebutton
keyManager<--Button2Chord
ChordButtonManager <-- Button2Chord

@enduml
