@startuml hoge
title "ループ全体の流れ"
participant rightButtonManager
participant allClassManager
participant GuitarNotePlayer
participant GuitarChord
participant Button2Chord
participant ChordButtonManager

allClassManager -> ChordButtonManager: updateState()
ChordButtonManager -> ChordButtonManager: update_vkb_state()
ChordButtonManager -> ChordButtonManager: update_vcb_state()

allClassManager -> rightButtonManager: getRightButtonState()（未実装）

allClassManager <-- rightButtonManager: getRightButtonState()（未実装）
alt 右手ボタンが押されていた
    alt 右手ボタンが押され始めている（さっきまで押されてなかった）
        allClassManager -> GuitarNotePlayer: updateNote()
        GuitarNotePlayer -> GuitarChord : generateNote()
        GuitarChord -> Button2Chord : updateChord()
        Button2Chord -> ChordButtonManager: getVirtualChordButtons()
        Button2Chord <--ChordButtonManager : getVirtualChordButtons()
        GuitarChord -> Button2Chord: getChordName()
        GuitarChord <-- Button2Chord: getChordName()
        GuitarNotePlayer -> GuitarChord : getNotes()
        GuitarNotePlayer <-- GuitarChord : getNotes()
    end
        allClassManager -> GuitarNotePlayer : playNote(float time)
else 右手ボタンが押され終わった
    allClassManager -> GuitarNotePlayer: stopNote()
end

@enduml